name: integracion continua con node.js

on: [push, pull_request]

jobs:
  ci_to_main:
    runs-on: ubuntu-20.04
    container:
      image: "ubuntu:20.04"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Update apt and install required packages
        run: |
          apt update
          apt install --yes sudo
          sudo apt install --yes --no-install-recommends curl
      - name: Import the public key used by the package management system
        run: |
          sudo rm -f /etc/ssl/certs/ca-bundle.crt
          sudo apt reinstall --yes ca-certificates
          sudo update-ca-certificates
          curl -fsSL https://pgp.mongodb.com/server-6.0.asc | \
            sudo gpg -o /usr/share/keyrings/mongodb-server-6.0.gpg \
            --dearmor
      - run: sudo apt-get install --yes gnupg
      - run: wget -qO - https://www.mongodb.org/static/pgp/server-6.0.asc | sudo apt-key add - 
      - run: echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/6.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-6.0.list 
      - run: sudo apt-get update 
      - run: sudo apt-get install -y mongodb-org 

      - name: Start MongoDB
        run: sudo service mongodb start

      - name: Verify that MongoDB has started successfully
        run: echo $(sudo service mongodb status)

      - run: npm ci
      - name: Run tests
        env:
          DB_USER: 'mongoadmin'
          DB_PASS: 'secret'
          DB_HOST: 'localhost'
          DB_PORT: '27017'
          DB_NAME: 'mongodb-mongodb-1'
        run: |
          npm test
